### ISSUE TITLE
Tried to update the result in Testrail and getting Cannot read property 'pop' of undefined "

### ISSUE THREAD

**Issue by Manjulamadhu** [mvndaai/testrail-promise#10]
Hi,

First of all, thank you so much for your contributions.
I 'am currently working on Protractor Jasmine automation for angularjs web ui application
We are using Testrail for Testcase development
Our testcases are combination of manual and automated
Below are my clarifications
1. Can i use testrail-promise to update the automated test result in test rail

I tried using and getting Cannot read property 'pop' of undefined
"
2. Environment used:
node v6.10.2
protractor 5.1.1

3. I have done following and facing error as "Unhandled rejection TypeError: Cannot read property 'pop' of undefined
"
    at c:\Locksmith\WebUI_Automation\node_modules\testrail-promise\lib\helpers.js:104:41
    at tryCatcher (c:\Locksmith\WebUI_Automation\node_modules\request-promise\node_modules\bluebird\js\main\util.js:26:23)
    at Promise.module.exports.Promise._settlePromiseFromHandler (c:\Locksmith\WebUI_Automation\node_modules\request-promise\node_modules\bluebird\js\main\promise.js:510:31)
    at Promise.module.exports.Promise._settlePromiseAt (c:\Locksmith\WebUI_Automation\node_modules\request-promise\node_modules\bluebird\js\main\promise.js:584:18)
    at Promise.module.exports.Promise._settlePromises (c:\Locksmith\WebUI_Automation\node_modules\request-promise\node_modules\bluebird\js\main\promise.js:700:14)
    at Async._drainQueue (c:\Locksmith\WebUI_Automation\node_modules\request-promise\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (c:\Locksmith\WebUI_Automation\node_modules\request-promise\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.e.Async.drainQueues (c:\Locksmith\WebUI_Automation\node_modules\request-promise\node_modules\bluebird\js\main\async.js:15:14)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)

4. Install  npm install testrail-promise --save-dev
5. In TestRail Under 
TestRuns and Results , i added "TestPlan" 
6. I have added the following in test spec in Protractor Jasmine Framework

resultLeaker = {
	suiteStarted: function (result) { jasmine.results = { suite: result }; },
	specStarted: function (result) { jasmine.results.spec = result; }
};
jasmine.getEnv().addReporter(resultLeaker);

describe('Admin User login scenarios', function () {

	it('Sanity', function () {
		coreKeyword.OpenURL(config.hpsmURL);
		login.HPSMLogin(config.hpsmusername, config.hpsmpassword);
		expect(coreKeyword.pageTitle(config.hpsmsitemap, 'Dashboard', 'DashboardTitle').isDisplayed()).toBeTruthy();
	});
	var TestRail = require('testrail-promise');
	var tr = new TestRail("https://jiracso2.testrail.net/index.php?/dashboard", "username", "password");

	afterEach(function (done) {
		var obj = {
			"project_name": "HPSM1",
			"plan_name": "TestPlan",
			"section_name": "TestRun",
			"title": jasmine.results.spec.description,
			"status_name": (jasmine.results.spec.failedExpectations.length === 0 ? "passed" : "failed")

		};
		tr.allowUntrustedCertificate();

		tr.ifNeededCreateThenAddResultForCase(obj).finally(function () {
			done();
		});
	});

});

6. While debugging , following observation in 
Filename : Helpers.js 
Function : getLatestRunInPlan()
Variable : plans 
return
If you have gotten this web page, your browser is misconfigured.
</h1>

<br>
<br>
<ul id="menu" style="list-style-type:none">
<li><em>HPI</em> clients should 'Use automatic configuration script' <em>http://autocache.hpicorp.net/</em>.</li>
</ul>
<ul id="menu" style="list-style-type:none">
<li>1. From the Internet Explorer Tools menu, select Internet Options.</li>
<li>2. Select the Connections tab.</li>
<li>3. Select LAN Settings.</li>
<li>4. Uncheck Automatically detect settings, if it is currently checked.</li>
<li>5. Check Use automatic configuration script.</li>
<li>6. In the Address field, enter:  <em>http://autocache.hpicorp.net/</em> if you are an <em>HP Inc</em> client.</li>
<li>7. Uncheck Use a proxy server for your LAN.</li>
<li>8. Select OK twice.</li>
</ul>
<br>
<br>
<br>

</body></html>"
 I'am currently executing the test in chrome , why is this IE being used for testrail and IE is configured as per the recommendation in debug
Can you kindly help. It is extremely important to update the test result to Testrail

**Comment by mvndaai** [comment]
When I have some time I will try to add a better error for this. It looks like your line is erroring on https://github.com/mvndaai/testrail-promise/blob/master/lib/helpers.js#L104, which is trying to get a test plan. If you do not have a test plan created you will probably get this error. Try creating a test plan.

Maybe called the function `getLatestRunInPlan` on its own and see what happens.

**Comment by mvndaai** [comment]
If you want to add a pull request on how to handle that error more gracefully I would gladly accept it.

**Comment by Manjulamadhu** [comment]
![capture](https://cloud.githubusercontent.com/assets/20530008/26090771/a3c3838c-3a24-11e7-808e-6bfa37348f11.PNG)

Hi ,
I have created Test Plan and Test Run in TestRail->Test Runs and Results. Please refer the attached.
Please guide me if the mapping of Jira field in obj variable in correct.

Thanks once again
Regards,
Manjula

**Comment by mvndaai** [comment]
@Manjulamadhu can you retests this, I just pushed a change that checks if that property is defined.

**Comment by mvndaai** [comment]
I believe this is fixed. Reopen the bug if there are still issues @Manjulamadhu.
