### ISSUE TITLE
error: 'Invalid array argument in URI: /api/v2/add_result_for_case/' is seen

### ISSUE THREAD

**Issue by devlina21** [mvndaai/testrail-promise#12]
Hi, 
I was trying to run this:
`var resultLeaker = {
    suiteStarted: function (result) {
        jasmine.results = {suite: result};
    },
    specStarted: function (result) {
        jasmine.results.spec = result;
    }
};
jasmine.getEnv().addReporter(resultLeaker);

describe('TestRail Reporter', function () {

    it('Passing', function () {
        expect(true).toBeTruthy();
    });
    it('Failing', function () {
        expect(false).toBeTruthy();
    });

    var TestRail = require("testrail-promise");
    var tr = new TestRail(url, user, password);

    tr.getProjects().then(function (projects) {
        console.log('These are all the projects ==>', projects)
    }).catch(function (err) {
        console.log('Error', err);
    });

    afterEach(function (done) {
        var obj = {
            "project_name": "project",
            "plan_name": "testProtractor",
            "section_name": "Test Run 5/15/2017",
            "suite_name": "testProtractor",
            "title": jasmine.results.spec.fullName,
            "status_name": (jasmine.results.spec.failedExpectations.length === 0 ? "passed" : "failed")
        };
        

        tr.ifNeededCreateThenAddResultForCase(obj)
            .then(function (result) {
                console.log('Result ==>', result);
            })
            .catch(function (err) {
                console.log('Error ==>', err);
            });

    });
});`

I am getting this error:
Result ==> { error: 'Invalid array argument in URI: /api/v2/add_result_for_case/' }

I'll appreciate any insights!

**Comment by mvndaai** [comment]
Can you run each of the commands for that function and tell me where the error actually is? I am no longer using Testrail actively but would love to help.
https://github.com/mvndaai/testrail-promise/blob/master/lib/helpers.js#L146

**Comment by mvndaai** [comment]
I just pushed an update with that change. You should be able to do an `npm install` to get that change. Thank you so much!
