### ISSUE TITLE
The response is not in JSON format

### ISSUE THREAD

**Issue by krthknan** [mvndaai/testrail-promise#17]
{ id: 2755,
  suite_id: 1558,
  name: 'Automation - Smoke Test Suite',
  description: null,
  milestone_id: null,
  assignedto_id: null,
  include_all: true,
  is_completed: false,
  completed_on: null,
  config: null,
  config_ids: [],
  passed_count: 0,
  blocked_count: 0,
  untested_count: 1,
  retest_count: 0,
  failed_count: 0,
  custom_status1_count: 0,
  custom_status2_count: 0,
  custom_status3_count: 0,
  custom_status4_count: 0,
  custom_status5_count: 0,
  custom_status6_count: 0,
  custom_status7_count: 0,
  project_id: 71,
  plan_id: null,
  created_on: 1542177918,
  created_by: 347,
  url:
   'https://testrail.companyName.com//index.php?/runs/view/2755' }

It is not in JSON format, so it is difficult to get the values

**Comment by mvndaai** [comment]
What do you mean by that? Do you mean that it is using underscores vs camelcase? What function are you calling?

**Comment by krthknan** [comment]
Hi,

I'm using the functions addRun, getRuns, getTests etc.

For example, addRun returns the following output, which is not in JSON format.

{ id: 2772,
  suite_id: 1558,
  name: 'Automation - Smoke Test Suite',
  description: null,
  milestone_id: null,
  assignedto_id: null,
  include_all: true,
  is_completed: false,
  completed_on: null,
  config: null,
  config_ids: [],
  passed_count: 0,
  blocked_count: 0,
  untested_count: 1,
  retest_count: 0,
  failed_count: 0,
  custom_status1_count: 0,
  custom_status2_count: 0,
  custom_status3_count: 0,
  custom_status4_count: 0,
  custom_status5_count: 0,
  custom_status6_count: 0,
  custom_status7_count: 0,
  project_id: 71,
  plan_id: null,
  created_on: 1542351334,
  created_by: 347,
  url:
   'https://testrail.companyName.com//index.php?/runs/view/2772' }

Sample JSON format :
{
  "siteURL": "Google"
}

The Key and Values are not surrounded with double quotes.

Kindly do the needful.

**Comment by mvndaai** [comment]
If you need to change it from a JavaScript Object to a JSON object you can just use `JSON.stringify()`.

**Comment by krthknan** [comment]
Yeah, It's working for me. JSON.stringify()

**Comment by krthknan** [comment]
Working Fine
