### ISSUE TITLE
Typescript code to integrate TestRail

### ISSUE THREAD

**Issue by krthknan** [mvndaai/testrail-promise#19]
I'm unable to integrate with TestRail by using this api, I have written code by using TypeScript. Kindly provide a sample code for addRun, getTests, getRun etc.

**Comment by mvndaai** [comment]
I have never used TypeScript so I don't know what you need to do to run this with it. You may have to create types for each object that is returned. I am not sure. Here are some places to start looking into answers:
https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Modules.md#working-with-other-javascript-libraries
https://stackoverflow.com/a/26505153/2249725

**Comment by krthknan** [comment]
I'm unable to call a javascript function (like addRun, getCase, addCase etc..) from typescript code.
If possible please provide the input for this

**Comment by mvndaai** [comment]
This is a vanilla JavaScript package. If you want to use it in typescript you have to figure out how that works.
