### ISSUE TITLE
typeof obj.section_id !== undefined does not work as intended

### ISSUE THREAD

**Issue by CTaylor1118** [mvndaai/testrail-promise#2]
There are several of these type of checks in the code and they do not work in the property is not actually defined. typeof obj.suite when it is undefined is the string _'undefined'_ so either the check should be 
```javascript
if (typeof obj.section_id !== 'undefined') path += "&section_id=" + obj.section_id;
```

or more conveniently since undefined is falsey
```javascript
if (obj.section_id) path += "&section_id=" + obj.section_id;
```

of course there are better ways to verify the values but this should be good enough.

**Comment by mvndaai** [comment]
Thank you for the feedback. Since you already changed them in your own fork if you do a pull request I will check it and accept it. Otherwise it will wait till I have the time, probably next week.

**Comment by mvndaai** [comment]
Thank you, I merged your code but changed a bit to pass my jslint linter.
[Here is the commit.](https://github.com/mvndaai/testrail-promise/commit/3f19111417d14de2f7ee6b8920b67e835ed48c6d) Let me know if you find anything else
