### ISSUE TITLE
Failed: Cannot read property 'description' of undefined

### ISSUE THREAD

**Issue by NadinFarbman** [mvndaai/testrail-promise#5]
Hi,

I try run a Jasmine test according to your example, but receive the following error:
>  Failed: Cannot read property 'description' of undefined

I changed the obj body as below, just to see a result in TestRail env:

var testRailTitle = this.getFullName();
var obj ={
           "project_name": "my Test",
            "plan_name": "UI Unit Tests",
            "section_name": testRailTitle,
            "title": testRailTitle+ " " + testRailTitle,
             "status_name":  "passed"
};
        tr.ifNeededCreateThenAddResultForCase(obj).finally(function () {
            done();
        });

BUT receive the following rejection:

>  Unhandled rejection TypeError: Cannot read property 'pop' of undefined
>     at c:\dev\PWS_Auto_Test\RMS\RMS\node_modules\testrail-promise\lib\helpers.js:88:41
>     at tryCatcher (c:\dev\PWS_Auto_Test\RMS\RMS\node_modules\testrail-promise\node_modules\bluebird\js\main\util.js:26:23)
>     at Promise._settlePromiseFromHandler (c:\dev\PWS_Auto_Test\RMS\RMS\node_modules\testrail-promise\node_modules\bluebird\js\main\promise.js:510:31)
>     at Promise._settlePromiseAt (c:\dev\PWS_Auto_Test\RMS\RMS\node_modules\testrail-promise\node_modules\bluebird\js\main\promise.js:584:18)
>     at Promise._settlePromises (c:\dev\PWS_Auto_Test\RMS\RMS\node_modules\testrail-promise\node_modules\bluebird\js\main\promise.js:700:14)
>     at Async._drainQueue (c:\dev\PWS_Auto_Test\RMS\RMS\node_modules\testrail-promise\node_modules\bluebird\js\main\async.js:123:16)
>     at Async._drainQueues (c:\dev\PWS_Auto_Test\RMS\RMS\node_modules\testrail-promise\node_modules\bluebird\js\main\async.js:133:10)
>     at Immediate.Async.drainQueues [as _onImmediate] (c:\dev\PWS_Auto_Test\RMS\RMS\node_modules\testrail-promise\node_modules\bluebird\js\main\async.js:15:14)
>     at processImmediate [as _immediateCallback] (timers.js:383:17)

BTW the "status_name":(this.results_.failedCount === 0 ? "passed" : "failed") is not valid as well. In this case I receive the following error:
>     - Failed: Cannot read property 'failedCount' of undefined

I use jasmine v2.4.1 + protractor (JS). 
Could you please help me to fix the issue?

Thanks in advance

**Comment by mvndaai** [comment]
Jasmine recently changed to not have anything in it's "this" object. I am looking for another way to get the info, but I haven't found it yet.

**Comment by NadinFarbman** [comment]
Thank you for your response, Jason.

Could you please explain me the following case?

Suppose there is no "this" object of Jasmine...
My purpose is to create a project in TestRail with the following parameters: 
>  var OBJ= {
>             "project_name": "Test",
>             "plan_name": "Plane",
>             "section_name": "testing",
>             "title": 'TEST',
>             "status": "passed"
>         };
>         return tr.ifNeededCreateThenAddResultForCase(OBJ);

But, in this case I receive the following error:

> **Unhandled rejection TypeError: Cannot read property '**pop**' of undefined**
> at xxx\testrail-promise\lib\helpers.js:88:41
> at tryCatcher (xxx\testrail-promise\node_modules\bluebird\js\main\util.js:26:23)
> at Promise._settlePromiseFromHandler (xxx\testrail-promise\node_modules\bluebird\js\main\promise.js:510:31)
> at Promise._settlePromiseAt (xxx\testrail-promise\node_modules\bluebird\js\main\promise.js:584:18)
> at Promise._settlePromises (xxx\testrail-promise\node_modules\bluebird\js\main\promise.js:700:14)
> at Async._drainQueue (xxx\testrail-promise\node_modules\bluebird\js\main\async.js:123:16)
> at Async._drainQueues (xxx\testrail-promise\node_modules\bluebird\js\main\async.js:133:10)
> at Immediate.Async.drainQueues as _onImmediate
> at processImmediate as _immediateCallback

Is the OBJ not valid for importing to TestRail ?

Thanks.

**Comment by mvndaai** [comment]
I need to put some error checking around that. I noticed the same error yesterday. It looks like it is having trouble getting the most recent Test Run in a Test Plan. You might want to look at the helper file and look what it is doing and check which point it errors at.

**Comment by mvndaai** [comment]
https://github.com/mvndaai/testrail-promise/blob/master/lib/helpers.js#L117

**Comment by mvndaai** [comment]
I figured out a way to let Protractor report again. The readme is updated in the commit below. I opened a new ticket #6  for the second error.

https://github.com/mvndaai/testrail-promise/commit/25b8645ecab013e1204dc7bf455425baf2e84b0a

**Comment by mvndaai** [comment]
The pop issue if fixed. Thanks for the help!

**Comment by NadinFarbman** [comment]
Thank you for the feature :)
