### ISSUE TITLE
Error sending Protractor test results to testRail

### ISSUE THREAD

**Issue by Emilemuny** [mvndaai/testrail-promise#9]
`var resultLeaker = {
  suiteStarted: function(result){ jasmine.results = {suite:result}; },
  specStarted: function(result){ jasmine.results.spec = result; }
};
jasmine.getEnv().addReporter(resultLeaker);

describe('TestRail Reporter', function(){

  it('Passing', function(){
    expect(true).toBeTruthy();
  });
  it('Failing', function(){
    expect(false).toBeTruthy();
  });

  var TestRail = require("testrail-promise");
  var tr = new TestRail('url', 'usr', 'pwd');

  tr.getProjects().then(function(projects){
    console.log('These are all the projects ==>', projects)
  }).catch(function(err){
    console.log('Error', err);
  });

  afterEach(function(done){
    var obj = {
      "project_id":"P4",
      "plan_name": "test"
      "section_name":"Login Page ",
      "title": jasmine.getEnv().currentSpec.getFullName(),
      "status_name":(jasmine.getEnv().currentSpec.results_.passedCount.length === 0 ? "passed" : "failed")
    };
    tr.ifNeededCreateThenAddResultForCase(obj)
      .then(function (result) { console.log('Result ==>', result); })
      .catch(function (err) { console.log('Error ==>', err); });

  });
});`

Running the above code to report the test results to testRail throws error 
{ error: 'Field :run_id is not a valid ID.' } 
Could please direct me where i should provide run id if that's the issue ?

**Comment by mvndaai** [comment]
I thought that it auto found it, but if not just add it to your `obj`.

```
var obj = {
"project_id":"P4",
"plan_name": "test"
"section_name":"Login Page ",
"title": jasmine.getEnv().currentSpec.getFullName(),
"status_name":(jasmine.getEnv().currentSpec.results_.passedCount.length === 0 ? "passed" : "failed")
};
```

**Comment by Emilemuny** [comment]
I keep getting errors requiring case_id, run_id but as the object passed to ifNeededCreateThenAddResultForCase() does not really need case_id or run_id. All i need to do is send protractor test results to test rail, create test cases if not existent.

**Comment by mvndaai** [comment]
Something is not right, `ifNeededCreateThenAddResultForCase` should create or find the case_id based on the title.

**Comment by Emilemuny** [comment]
@mvndaai i apologize. Things works just fine when i added the proper plan_name value. I  am new to testrail and wasn't sure about the test plan parameter.  Thanks for your support! Please feel free to close issue.

**Comment by mvndaai** [comment]
Awesome! I am glad it worked out. Thanks.
